### PR TITLE
Add new library

### PR DESCRIPTION
**Pull request by ercand**
{  
   "owner":"ercand",
   "repo":"CottontailSummoners",
   "description":"LeagueOfLegends v3 API wrapper. Website in asp.net MVC like www.op.gg",
   "language":"C#",
   "links":[  
      {  
         "name":"NuGet",
         "url":"https://github.com/ercand/CottontailSummoners/"
      }
   ],
   "metadata":{  
      "v3": true,
      "rate-limiter":{
         "header-driven":true,
         "method-rate-limiting":true,
         "per-region":true,
         "per-endpoint":true
       }
   },
   "tags":[  
       "v3",
       "rate-limiter"
   ]
}

### CODE REVIEW

**Comment by WxWatch** [comment]
I don't actually want to use the `gh-pages` branch anymore, so we don't need this.

**Comment by ercand** [comment]
WxWatch What should i have to do?

**Comment by WxWatch** [comment]
Fork this repo, make your changes and then submit a pull request to merge your changes back into this repo.

**Comment by ercand** [comment]
I have to press Fork button?Then?
I'm realy sorry, first time i use GitHub

**Comment by ercand** [comment]
Can help me pls?

**Pull request closed without merging**
