### PR TITLE
Api riot games javascript library def

### PR DESCRIPTION
**Pull request by Sansossio**

### CODE REVIEW

**Comment by jjmaldonis** [comment]
No one merge this yet.

@Sansossio What is the purpose of this PR? It looks like it adds examples for the `kayn` API wrapper.

**Comment by Sansossio** [comment]
@jjmaldonis totally my fault, I forgot to update module references.
This is another npm package wrap to riot api.
Now it's updated.

**Comment by jjmaldonis** [comment]
Ok cool. It's awesome that you're supporting TFT already. My hesitancy in clicking merge is that the name of the library is super generic. Do you want to rename it to something else? It will make your library much more google-able when people are looking for it.

**Comment by Sansossio** [comment]
You're right, the name was super generic, now its name is **twisted** 💃

**Comment by jjmaldonis** [comment]
Awesome! Thanks for contributing to the community!

**Pull request merged**
